   repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: "v0.2.1"
      hooks:
        - id: ruff
          args: ["--fix"]
        - id: ruff-format

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: fix-encoding-pragma
          args: [--remove]
      -   id: check-yaml
      -   id: debug-statements
          exclude: _pytest/(debugging|hookspec).py
          language_version: python3.10

    - repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
      -   id: flake8
          name: flake8
          types: [python]
          args:
          -   --max-line-length=88
          -   --ignore=E203,E501,W503
